datagrid:
    issues-grid:
        source:
#            acl_resource: inventory.vehicle_view
            type: orm
            query:
                select:
                    - distinct issue.id
                    - issue.code
                    - issue.summary
                    - type.label as typeLabel
                    - priority.label as priorityLabel
                    - status.label as statusLabel
                    - resolution.label as resolutionLabel
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as assigneeName
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: LuminaireIssueBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.type, alias: type}
                        - { join: issue.priority, alias: priority}
                        - { join: issue.status, alias: status}
                        - { join: issue.resolution, alias: resolution}
                        - { join: issue.reporter, alias: reporter}
                        - { join: issue.assignee, alias: assignee}
                        - { join: issue.collaborators, alias: collaborator}
        columns:
            code:
                label: luminaire.issue.code.label
            summary:
                label: luminaire.issue.summary.label
            typeLabel:
                label: luminaire.issue.type.label
            priorityLabel:
                label: luminaire.issue.priority.label
            statusLabel:
                label: luminaire.issue.status.label
            resolutionLabel:
                label: luminaire.issue.resolution.label
            reporterName:
                label: luminaire.issue.reporter.label
            assigneeName:
                label: luminaire.issue.assignee.label
            createdAt:
                label: luminaire.issue.created_at.label
                frontend_type: date
            updatedAt:
                label: luminaire.issue.updated_at.label
                frontend_type: date
        properties:
            id: ~
            update_link:
                type: url
                route: luminaire_issue_update
                params: [ id ]
            view_link:
                type: url
                route: luminaire_issue_show
                params: [ id ]
            delete_link:
                type: url
                route: luminaire_api_delete_issue
                params: [ id ]
        sorters:
            columns:
                code:
                    data_name: issue.code
                summary:
                    data_name: issue.summary
                typeLabel:
                    data_name: issue.type
                priorityLabel:
                    data_name: priority.order
                statusLabel:
                    data_name: status.order
                resolutionLabel:
                    data_name: resolution
                reporterName:
                    data_name: reporter
                assigneeName:
                    data_name: issue.assignee
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                code:
                    type:      number
                    data_name: issue.code
                summary:
                    type:      string
                    data_name: issue.summary
                typeLabel:
                    type: entity
                    data_name: issue.type
                    options:
                        field_options:
                            class: LuminaireIssueBundle:IssueType
                            property: label
                priorityLabel:
                    type: entity
                    data_name: issue.priority
                    options:
                        field_options:
                            class: LuminaireIssueBundle:IssuePriority
                            property: label
                statusLabel:
                    type: entity
                    data_name: issue.status
                    options:
                        field_options:
                            class: LuminaireIssueBundle:IssueStatus
                            property: label
                resolutionLabel:
                    type: entity
                    data_name: issue.resolution
                    options:
                        field_options:
                            class: LuminaireIssueBundle:IssueResolution
                            property: label
                reporterName:
                    type: entity
                    data_name: reporter.id
                    options:
                        field_options:
                            class: OroUserBundle:User
                            property: username
                assigneeName:
                    type: entity
                    data_name: assignee.id
                    options:
                        field_options:
                            class: OroUserBundle:User
                            property: username
                createdAt:
                    type:      date
                    data_name: issue.createdAt
                updatedAt:
                    type:      date
                    data_name: issue.updatedAt
                collaborators:
                    label: luminaire.issue.collaborators.label
                    type: entity
                    data_name: collaborator.id
                    options:
                        field_options:
                            class: OroUserBundle:User
                            property: username
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
#                acl_resource:  inventory.vehicle_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
#                acl_resource:  inventory.vehicle_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
#                acl_resource:  inventory.vehicle_delete

    issue-collaborators-update-grid:
        source:
            type: orm
#            acl_resource: orocrm_contact_view
            query:
                select:
                    - user.id
                    - user.username
                    - >
                      CASE WHEN (user IN (:collaborators) or (user.id IN (:data_in) AND user.id NOT IN (:data_not_in)))
                       THEN true ELSE false END as isCollaborator
                from:
                    - { table: OroUserBundle:User, alias: user }
            bind_parameters:
                - collaborators
        columns:
            isCollaborator:
                label:         luminaire.issue.collaborators.label
                frontend_type: boolean
                editable:      true
            username:
                label:         oro.user.username.label
        sorters:
            columns:
                username: { data_name: user.username }
            default: { username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC }
        filters:
            columns:
                username:
                    data_name: user.username
                    type:      string
        properties:
            id: ~
        options:
            entityHint: user
            rowSelection:
                dataField: id
                columnName: isCollaborator
                selectors:
                    included: '#appendCollaborators'
                    excluded: '#removeCollaborators'

    issue-collaborators-grid:
        extends: users-grid
        source:
            query:
                where:
                    and:
                        - (u in (:collaborators))
            bind_parameters:
                - collaborators

    dashboard-collaborator-issues-grid:
        source:
#            acl_resource: inventory.vehicle_view
            type: orm
            query:
                select:
                    - distinct issue.id
                    - issue.code
                    - issue.summary
                    - issue.updatedAt
                from:
                    - { table: LuminaireIssueBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.status, alias: status}
                        - { join: issue.collaborators, alias: collaborator}
                where:
                    and:
                        - (status.name not in ('closed', 'resolved'))
                        - (collaborator = @oro_security.security_facade->getLoggedUserId)
        columns:
            code:
                label: luminaire.issue.code.label
            summary:
                label: luminaire.issue.summary.label
            updatedAt:
                label: luminaire.issue.updated_at.label
                frontend_type: date
        properties:
            id: ~
            update_link:
                type: url
                route: luminaire_issue_update
                params: [ id ]
            view_link:
                type: url
                route: luminaire_issue_show
                params: [ id ]
            delete_link:
                type: url
                route: luminaire_api_delete_issue
                params: [ id ]
        sorters:
            columns:
                code:
                    data_name: issue.code
                summary:
                    data_name: issue.summary
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
#                acl_resource:  inventory.vehicle_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
#                acl_resource:  inventory.vehicle_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
#                acl_resource:  inventory.vehicle_delete
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
