datagrid:
    issues-grid:
        source:
            acl_resource: luminaire_issue_view
            type: orm
            query:
                select:
                    - distinct issue.id
                    - issue.id
                    - issue.summary
                    - type.label as typeLabel
                    - priority.label as priorityLabel
                    - resolution.label as resolutionLabel
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as assigneeName
                    - reporter.id as reporterId
                    - assignee.id as assigneeId
                    - issue.createdAt
                    - issue.updatedAt
                    - workflowStep.label as workflowStepLabel
                from:
                    - { table: %luminaire_issue.entity.issue.class%, alias: issue }
                join:
                    left:
                        - { join: issue.type, alias: type}
                        - { join: issue.priority, alias: priority}
                        - { join: issue.resolution, alias: resolution}
                        - { join: issue.reporter, alias: reporter}
                        - { join: issue.assignee, alias: assignee}
                        - { join: issue.collaborators, alias: collaborator}
                        - { join: issue.workflowStep, alias: workflowStep }
        columns:
            id:
                label: luminaire.issue.id.label
            summary:
                label: luminaire.issue.summary.label
            typeLabel:
                label: luminaire.issue.type.label
            priorityLabel:
                label: luminaire.issue.priority.label
            workflowStepLabel:
                label: luminaire.issue.workflow_step.label
            resolutionLabel:
                label: luminaire.issue.resolution.label
            reporterName:
                label: luminaire.issue.reporter.label
                type: twig
                frontend_type: html
                template: LuminaireIssueBundle:Issue:Datagrid/Property/reporter.html.twig
            assigneeName:
                label: luminaire.issue.assignee.label
                type: twig
                frontend_type: html
                template: LuminaireIssueBundle:Issue:Datagrid/Property/assignee.html.twig
            createdAt:
                label: luminaire.issue.created_at.label
                frontend_type: datetime
            updatedAt:
                label: luminaire.issue.updated_at.label
                frontend_type: datetime
        properties:
            id: ~
            update_link:
                type: url
                route: luminaire_issue_update
                params: [ id ]
            view_link:
                type: url
                route: luminaire_issue_show
                params: [ id ]
            delete_link:
                type: url
                route: luminaire_api_delete_issue
                params: [ id ]
        sorters:
            columns:
                id:
                    data_name: issue.id
                summary:
                    data_name: issue.summary
                typeLabel:
                    data_name: type.order
                priorityLabel:
                    data_name: priority.order
                workflowStepLabel:
                    data_name: workflowStep.stepOrder
                resolutionLabel:
                    data_name: resolution.order
                reporterName:
                    data_name: reporter
                assigneeName:
                    data_name: issue.assignee
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                id:
                    type:      number
                    data_name: issue.id
                summary:
                    type:      string
                    data_name: issue.summary
                typeLabel:
                    type: entity
                    data_name: issue.type
                    options:
                        field_options:
                            class: %luminaire_issue.entity.issue_type.class%
                            property: label
                priorityLabel:
                    type: entity
                    data_name: issue.priority
                    options:
                        field_options:
                            class: %luminaire_issue.entity.issue_priority.class%
                            property: label
                workflowStepLabel:
                    type:      entity
                    data_name: task.workflowStep
                    options:
                        field_type: oro_workflow_step_select
                        field_options:
                            workflow_entity_class: %luminaire_issue.entity.issue.class%
                resolutionLabel:
                    type: entity
                    data_name: issue.resolution
                    options:
                        field_options:
                            class: %luminaire_issue.entity.issue_resolution.class%
                            property: label
                reporterName:
                    type: entity
                    data_name: reporter.id
                    options:
                        field_options:
                            class: %oro_user.entity.class%
                            property: username
                assigneeName:
                    type: entity
                    data_name: assignee.id
                    options:
                        field_options:
                            class: %oro_user.entity.class%
                            property: username
                createdAt:
                    type:      date
                    data_name: issue.createdAt
                updatedAt:
                    type:      date
                    data_name: issue.updatedAt
                collaborators:
                    label: luminaire.issue.collaborators.label
                    type: entity
                    data_name: collaborator.id
                    options:
                        field_options:
                            class: %oro_user.entity.class%
                            property: username
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  luminaire_issue_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  luminaire_issue_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  luminaire_issue_delete

    issue-collaborators-update-grid:
        source:
            type: orm
            acl_resource: luminaire_issue_view
            query:
                select:
                    - user.id
                    - user.username
                    - >
                      CASE WHEN (user IN (:collaborators) or (user.id IN (:data_in) AND user.id NOT IN (:data_not_in)))
                       THEN true ELSE false END as isCollaborator
                from:
                    - { table: %oro_user.entity.class%, alias: user }
            bind_parameters:
                - collaborators
        columns:
            isCollaborator:
                label:         luminaire.issue.collaborators.label
                frontend_type: boolean
                editable:      true
            username:
                label:         oro.user.username.label
        sorters:
            columns:
                username: { data_name: user.username }
            default: { username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC }
        filters:
            columns:
                username:
                    data_name: user.username
                    type:      string
        properties:
            id: ~
        options:
            entityHint: user
            rowSelection:
                dataField: id
                columnName: isCollaborator
                selectors:
                    included: '#appendCollaborators'
                    excluded: '#removeCollaborators'
            toolbarOptions:
                addResetAction: false
                addRefreshAction: false

    issue-collaborators-grid:
        source:
            type: orm
            acl_resource: luminaire_issue_view
            query:
                select:
                    - collaborator.username
                from:
                    - { table: %luminaire_issue.entity.issue.class%, alias: issue }
                join:
                    inner:
                        - { join: issue.collaborators, alias: collaborator}
                where:
                    and:
                        - (issue = :issue)
            bind_parameters:
                - issue
        columns:
            username:
                label: oro.user.username.label
        sorters:
            columns:
                username: { data_name: collaborator.username }
        filters:
            columns:
                username:
                    data_name: collaborator.username
                    type:      string

    dashboard-collaborator-issues-grid:
        source:
            acl_resource: luminaire_issue_view
            type: orm
            query:
                select:
                    - distinct issue.id
                    - issue.id
                    - issue.summary
                    - issue.updatedAt
                from:
                    - { table: %luminaire_issue.entity.issue.class%, alias: issue }
                join:
                    inner:
                        - { join: issue.collaborators, alias: collaborator}
                where:
                    and:
                        - (collaborator = @oro_security.security_facade->getLoggedUserId)
        columns:
            id:
                label: luminaire.issue.id.label
            summary:
                label: luminaire.issue.summary.label
            updatedAt:
                label: luminaire.issue.updated_at.label
                frontend_type: datetime
        properties:
            id: ~
            update_link:
                type: url
                route: luminaire_issue_update
                params: [ id ]
            view_link:
                type: url
                route: luminaire_issue_show
                params: [ id ]
            delete_link:
                type: url
                route: luminaire_api_delete_issue
                params: [ id ]
        sorters:
            columns:
                id:
                    data_name: issue.id
                summary:
                    data_name: issue.summary
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  luminaire_issue_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  luminaire_issue_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  luminaire_issue_delete
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10

    assignee-issues-grid:
        extends: issues-grid
        source:
            query:
                where:
                    and:
                        - (issue.assignee = :user_id)
            bind_parameters:
                - user_id
        filters:
            columns:
                assigneeName:
                    type: entity
                    data_name: assignee.id
                    options:
                        field_options:
                            class: %oro_user.entity.class%
                            property: username
                    enabled: false

    reporter-issues-grid:
        extends: issues-grid
        source:
            query:
                where:
                    and:
                        - (issue.reporter = :user_id)
            bind_parameters:
                - user_id
        filters:
            columns:
                reporterName:
                    type: entity
                    data_name: reporter.id
                    options:
                        field_options:
                            class: %oro_user.entity.class%
                            property: username
                    enabled: false
