placeholders:
    view_content_data_additional_information:
        items:
            orocrm_user_assigned_issues_grid: ~
            orocrm_user_reported_issues_grid: ~

items:
    orocrm_user_assigned_issues_grid:
        template: LuminaireIssueBundle:Issue:assigneeIssues.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
    orocrm_user_reported_issues_grid:
        template: LuminaireIssueBundle:Issue:reporterIssues.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
