placeholders:
    view_content_data_additional_information:
        items:
            luminaire_user_assigned_issues_grid: ~
            luminaire_user_reported_issues_grid: ~

items:
    luminaire_user_assigned_issues_grid:
        template: LuminaireIssueBundle:Issue:assigneeIssues.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)

    luminaire_user_reported_issues_grid:
        template: LuminaireIssueBundle:Issue:reporterIssues.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)

    luminiare_issue_create_button:
        template: LuminaireIssueBundle:Issue:createIssueButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: luminaire_issue_create

    luminiare_issue_create_link:
        template: LuminaireIssueBundle:Issue:createIssueLink.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: luminaire_issue_create
