definitions:
    issue_definition:
        label: Update issue collaborators
        enabled: true
        entity: Luminaire\Bundle\IssueBundle\Entity\Issue
        order: 20
        exclude_definitions: [issue_definition]
        actions_configuration:
            - @call_method:
                conditions:
                    @not_empty: $assignee
                object: $.data
                method: addCollaborator
                method_parameters: [$assignee]
            - @call_method:
                object: $.data
                method: addCollaborator
                method_parameters: [$reporter]

    issue_notes_definition:
        label: Update issue notes
        enabled: true
        entity: Oro\Bundle\NoteBundle\Entity\Note
        order: 20
        exclude_definitions: [issue_notes_definition]
        actions_configuration:
            - @tree:
                conditions:
                    @note_target:
                        note: $.data
                        targetClass: Luminaire\Bundle\IssueBundle\Entity\Issue
                actions:
                    - @call_method:
                        object: $target
                        method: addCollaborator
                        method_parameters: [$owner]
                    - @call_method:
                        object: $target
                        method: addCollaborator
                        method_parameters: [$updatedBy]

triggers:
    issue_definition:
        -
            event: create
        -
            event: update

    issue_notes_definition:
        -
            event: create
        -
            event: update

