parameters:
    luminaire_issue.condition.note_target.class: Luminaire\Bundle\IssueBundle\ConfigExpression\Condition\NoteTarget
    luminaire_issue.entity.issue.class: Luminaire\Bundle\IssueBundle\Entity\Issue
    luminaire_issue.issue.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    luminaire_issue.handler.request_collaborator.class: Luminaire\Bundle\IssueBundle\Handler\RequestCollaboratorHandler
    luminaire_issue.event_listener.datagrid.class: Luminaire\Bundle\IssueBundle\EventListener\DatagridListener

services:
    luminaire_issue.issue.manager.api:
        class: %luminaire_issue.issue.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %luminaire_issue.entity.issue.class%
            - @doctrine.orm.entity_manager

    luminaire_issue.condition.note_target:
        class: %luminaire_issue.condition.note_target.class%
        tags:
            - { name: oro_workflow.condition, alias: note_target }

    luminaire_issue.event_listener.datagrid:
        class: %luminaire_issue.event_listener.datagrid.class%
        arguments:
            - @luminaire_issue.handler.request_collaborator
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre.issues-grid, method: onPreBuildIssues }

    luminaire_issue.handler.request_collaborator:
        class: %luminaire_issue.handler.request_collaborator.class%
        arguments:
            - @request_stack
            - @security.token_storage
