parameters:
    luminaire_issue.entity.issue.class: Luminaire\Bundle\IssueBundle\Entity\Issue
    luminaire_issue.issue.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    luminaire_issue.issue.manager.api:
        class: %luminaire_issue.issue.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %luminaire_issue.entity.issue.class%
            - @doctrine.orm.entity_manager
