parameters:
    luminaire_issue.condition.note_target.class: Luminaire\Bundle\IssueBundle\ConfigExpression\Condition\NoteTarget
    luminaire_issue.entity.issue.class: Luminaire\Bundle\IssueBundle\Entity\Issue
    luminaire_issue.entity.issue_type.class: Luminaire\Bundle\IssueBundle\Entity\IssueType
    luminaire_issue.entity.issue_priority.class: Luminaire\Bundle\IssueBundle\Entity\IssuePriority
    luminaire_issue.entity.issue_resolution.class: Luminaire\Bundle\IssueBundle\Entity\IssueResolution
    luminaire_issue.issue.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    luminaire_issue.handler.request_collaborator.class: Luminaire\Bundle\IssueBundle\Handler\RequestCollaboratorHandler
    luminaire_issue.issue_entity_name_provider.class: Luminaire\Bundle\IssueBundle\Provider\IssueEntityNameProvider
    luminaire_issue.validator.issue_subtask_parent_validator.class: Luminaire\Bundle\IssueBundle\Validator\IssueSubtaskParentValidator
    luminaire_issue.validator.issue_resolved_resolution_validator.class: Luminaire\Bundle\IssueBundle\Validator\IssueResolvedResolutionValidator

services:
    luminaire_issue.issue.manager.api:
        class: %luminaire_issue.issue.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %luminaire_issue.entity.issue.class%
            - @doctrine.orm.entity_manager

    luminaire_issue.condition.note_target:
        class: %luminaire_issue.condition.note_target.class%
        tags:
            - { name: oro_workflow.condition, alias: note_target }

    luminaire_issue.handler.request_collaborator:
        class: %luminaire_issue.handler.request_collaborator.class%
        arguments:
            - @request_stack
            - @security.token_storage

    luminaire_issue.issue_entity_name_provider:
        class: %luminaire_issue.issue_entity_name_provider.class%
        public: false
        tags:
            - { name: oro_entity.name_provider, priority: 0 }

    luminaire_issue.validator.issue_resolved_resolution_validator:
        class: %luminaire_issue.validator.issue_resolved_resolution_validator.class%
        arguments:
            - @translator
        tags:
            - { name: validator.constraint_validator, alias: luminaire_issue.validator.issue_resolved_resolution_validator }

    luminaire_issue.validator.issue_subtask_parent_validator:
        class: %luminaire_issue.validator.issue_subtask_parent_validator.class%
        arguments:
            - @translator
        tags:
            - { name: validator.constraint_validator, alias: luminaire_issue.validator.issue_subtask_parent_validator }

    luminaire_issue.widget_provider.actions.create_issue:
        parent: oro_ui.widget_provider.action_button.abstract
        arguments:
            - luminiare_issue_create_button
            - luminiare_issue_create_link
        tags:
            - { name: oro_ui.view_action_provider, group: activity }
