luminaire_issue_bundle:
    resource: "@LuminaireIssueBundle/Controller/IssueController.php"
    type: annotation

luminaire_bundle_api:
    resource:     "@LuminaireIssueBundle/Resources/config/oro/routing_api.yml"
    prefix:       api/rest/{version}/
    requirements:
        version:  latest|v1
        _format:  json
    defaults:
        version:  latest
